import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import Button from '@mui/material/Button';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className="flex-row space-between">
          <div className="logo-container pointer flex-row gap-10 align-center">
            <div className="img-container">
              <Image src="/images/hdc-logo.png" alt="HDC Logo" fill />
            </div>
            <div className="weight-600">HUGE DIGITAL CLOCK</div>
          </div>
          <div className="nav-right flex-row gap-20 body-text weight-500">
            <div className="link flex-column justify-center">Why HDC
            </div>
            <div className="link flex-column justify-center" >Blog</div>
            <Button color="primary" variant="contained" className="install-now-button align-self-center">Install Now</Button>
            {/* <button color="primary" className="install-now-button align-self-center">Install Now</button> */}
          </div>
          <div className="mobile-nav-right flex-column gap-20">

            <div
              className="flex-column justify-center align-center full-height heading-style-three">

            </div>
            <div
              className="flex-column justify-center align-center full-height heading-style-three" >
            </div >
            <div className="mobile-menu"  >
              <div className="link flex-column justify-center pointer"
              > Why HDC</div >
              <div className="link flex-column justify-center pointer"  >
                Blog</div >

            </div >
          </div >
        </nav >
      </header >
      <div className="home">
        <div className="home-section-one flex-row">
          <div className="left flex-column justify-center">
            <div className="flex-column text-align-center-responsive">
              <h2 className="heading-style-five" color="text-color">Always On, <span color="primary"> Always Chic</span></h2>
              <p className="body-text" color="primary-black">Huge Digital Clock App - big, bold, and customizable to your heart's desire! With a clean and minimalistic interface, this app is the perfect blend of functionality and style.                </p>

            </div>
            <div className="flex-row google-apple-link-container gap-40 mobile-hide flex-wrap">
              <div className="img-container">
                <a href="https://play.google.com/store/apps/details?id=com.cama.app.huge80sclock&hl=en_IN&gl=US"
                  target="_blank" >
                  <Image className="pointer" src="/images/get-it-on-gp.png" alt="HDC google play link" fill />
                </a>
              </div>
              <div className="img-container">
                <a href="https://apps.apple.com/in/app/huge-digital-clock/id1515003825" target="_blank">
                  <Image className="pointer" src="/images/get-it-on-apple.png"
                    alt="HDC apple store link" fill />
                </a>
              </div>
            </div>
          </div>
          <div className="right">
            <div className="img-container">
              <Image src="/images/hdc-home-bg-min.webp" alt="Huge Digital Clock" fill />
            </div>
          </div>
          <div className="flex-row google-apple-link-container gap-40 mobile-show">
            <div className="img-container">
              <a href="https://play.google.com/store/apps/details?id=com.cama.app.huge80sclock&hl=en_IN&gl=US" target="_blank">
                <Image className="pointer" src="/images/get-it-on-gp.png" alt="HDC google play link" fill />
              </a>
            </div>
            <div className="img-container">
              <a href="https://apps.apple.com/in/app/huge-digital-clock/id1515003825" target="_blank">
                <Image className="pointer" src="/images/get-it-on-apple.png"
                  alt="HDC apple store link" fill />
              </a>
            </div>
          </div >
        </div >
        <div className="home-section-two">
          <div>
            <div className="flex-row justify-center">
              <h2 className="heading-style-five" color="text-color">Huge Digital Clock
                <span color="primary"> Features</span>
              </h2>
            </div>
            <div className="grid-container">
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Extra-large digital clock" src="/images/extra-large-digital-clock.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Extra-large digital clock</div>
                  <p className="text-align-center " color="off-white">See clearly without glasses.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Clean design" src="/images/clean-design.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Clean design</div>
                  <p className="text-align-center " color="off-white">Simple yet stylish designs.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Night Mode" src="/images/night-mode.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Night Mode</div>
                  <p className="text-align-center " color="off-white"> Easy on eye.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Flexible Display" src="/images/flexible-display.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Flexible Display</div>
                  <p className="text-align-center " color="off-white"> Portrait or Landscape Mode.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image src="/images/weather-information.svg" width="80" height="80" alt="Weather Information" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Weather Information</div>
                  <p className="text-align-center " color="off-white">Stay informed.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Timer" src="/images/timer.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Timer</div>
                  <p className="text-align-center " color="off-white">Measure time intervals.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Customization" src="/images/customization.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Customization</div>
                  <p className="text-align-center " color="off-white">Themes, Colors, Font & more.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="12/24 hr" src="/images/12-24hr.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">12/24 hr</div>
                  <p className="text-align-center " color="off-white">Choose your Clock Orientation.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Screensaver" src="/images/screensaver.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Screensaver</div>
                  <p className="text-align-center " color="off-white">Always keep track of time.</p>
                </div>
              </div>
              <div className="flex-column gap-40 align-center">
                <div className="grid-img-container">
                  <Image alt="Android Alarm System" src="/images/android-alarm-system.svg" width="80" height="80" />
                </div>
                <div className="flex-column gap-10 align-center">
                  <div className="body-text weight-600">Android Alarm System</div>
                  <p className="text-align-center " color="off-white">Reliable.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="home-section-three"  >
          <div className="flex-row gap-40 justify-center align-center heading-container">
            <h2 className="flex-row justify-center heading-style-five" color="text-color">Testimonials</h2>

          </div>


        </div >

      </div >
      <footer className="flex-column gap-40">
        <div className="top flex-column align-center" >
          <h2 className="heading-style-four text-align-center" color="primary"
            style={{color:"var(--text-color)"}}>
            Day or Night, <span style={{color:"var(--primary)"}}>always in Sight!</span>
          </h2>
          <h3 style={{color:"var(--text-color)"}} className="heading-style-six weight-400 text-align-center">Download Huge
            Digital Clock now!
          </h3>
          <div className="flex-row google-apple-link-container gap-40">
            <div className="img-container">
              <Image alt="HDC Google Play Link" className="pointer" src="/images/get-it-on-gp.png" fill />
            </div>
            <div className="img-container">
              <Image alt="HDC Apple Store Link" className="pointer" src="/images/get-it-on-apple.png" fill />
            </div>
          </div>
        </div>
        <div className="bottom flex-column gap-60">
          <div className="footer-grid-container">
            <div className="flex-column gap-30">
              <div className="logo-container flex-row gap-10 align-center">
                <div className="img-container">
                  <Image src="/images/hdc-logo-transparent.png" alt="HDC Logo" fill />
                </div>
                <span className="weight-600">HUGE DIGITAL CLOCK</span>
              </div>
              <p className="medium-text">
                This is a huge digital clock, the biggest! It reproduces the fabulous display of a digital
                clock. The display is always on. The design is customizable.
              </p>
            </div>
            <div className="flex-column gap-30">
              <div>
                <h2 className="body-text">About Us</h2>
              </div>
              <div className="flex-column gap-5 footer-link-container medium-text">
                <div className="pointer">Home</div>
                <a href='https://kalagato.ai/huge-digital-clock-privacy-policy/' target="_blank"
                  className="pointer remove-text-style">Privacy Policy</a>
              </div>
            </div>
            <div className="flex-column gap-30">
              <div>
                <h2 className="body-text">Important Links</h2>
              </div>
              <div className="flex-column gap-5 footer-link-container medium-text">
                <a href='https://huge80sclock.page.link/hdcweb' target="_blank" className="pointer remove-text-style">Huge
                  Digital Clock for Android</a>
                <a href='https://apps.apple.com/in/app/huge-digital-clock/id1515003825'
                  target="_blank" className="pointer remove-text-style">Huge Digital Clock for iOS</a>
              </div>
            </div>
            <div className="flex-column gap-30">
              <h2 className="body-text">
                Contact Info
              </h2>
              <div className="flex-column medium-text">
                <span>KalaGato</span>
                <span>114 Lavender Street, CT Hub 2,</span>
                <span>#11-83(Lobby 1) Singapore</span>
                <span>338729</span>
                <a href="mailto:contactus@kalagato.co" target="_blank" className="remove-text-style">email:
                  contactus@kalagato.co</a>
                <a href="https://kalagato.ai/" target="_blank" className="remove-text-style pointer">Website:
                  https://kalagato.ai/</a>
              </div>
            </div>
          </div>
          <div className="flex-row space-between align-center copyright-social-container">
            <span>
              &#169; 2023 Huge Digital Clock - All Rights Reserved.
            </span>
            <div className="flex-row gap-10 social-icon-container">
              <div className="social-icon pointer">
                <Image alt="HDC Facebook link" src="/images/fb.svg" fill />
              </div>
              <div className="social-icon pointer">
                <Image alt="HDC Instagram link" src="/images/instagram.svg" fill />
              </div>
            </div>
          </div>
        </div>
      </footer >

    </>
  )
}
